name: Ensure code quality

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main]

jobs:
  Code Quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2

      - name: Change to the current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"

      - name: Install pipenv tool
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install project development dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Run sort imports
        run: |
          pipenv run isort $(find . -name '*.py')

      - name: Run linter
        run: |
          pipenv run pylint $(find . -name '*.py')

      - name: Run static type checker
        run: |
          pipenv run mypy $(find . -name '*.py')
