name: Run unit, integration and end-to-end

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2

      - name: Change to the current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Build image
        run: docker compose build
